name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: 🔍 Lint & Type-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dev dependencies
        run: uv sync --dev

      - name: isort — проверка импортов
        run: uv run isort --check-only src

      - name: flake8 — проверка стиля
        run: uv run flake8 src

      - name: mypy — статическая типизация
        run: uv run mypy src

  build-package:
    name: 📦 Build Python Package
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Build
        run: uv build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-package
          path: dist/
          retention-days: 90

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-package
          path: ./dist

  docker:
    name: 🐋 Build & Push Docker image
    permissions:
      contents: read
      packages: write
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ml-ops:latest
            ghcr.io/${{ github.repository_owner }}/ml-ops:${{ github.sha }}
